### PR TITLE
:sparkles: tentative to process multiple files ref: issue#24

### PR DESCRIPTION
**Pull request by Grogdunn**
Hi,

I'm not a Rust developer, but I've tried to hack your code to support multiple file processing in batch.

Can you try to see my work and throw away junk code (or do it better).

The hack just "works" but can be done better IMHO.

Grogdunn

### CODE REVIEW

**Comment by Grogdunn** [comment]
now should pass cargo fmt lint check :crossed_fingers:

**Comment by Grogdunn** [comment]
@avsaase can you validate the fmt fix? What do you think about that "workaround" to burn multiple files?

**Comment by avsaase** [comment]
Hi, thanks for contribution! I always planned to add something like a render queue similar to Gyroflow but I got stuck on deciding on the right UI to support that. I haven't looked at your code yet to see how you did this. I will try to review this later today.

**Comment by avsaase** [comment]
I have to say I don't like that this just grabs all the video files from the source folder without an option to select which ones to render. There should also be some way to see that multiple files are being rendered, ideally with some overview of the overall progress. 

This is not meant as a critique of your contribution, the way I "designed" this UI is just bad and it's difficult to add bulk processing in a clean way. If you have ideas on how that could look then I'm happy to discuss them and implement it myself. 

For now though, I will close this PR. 

Not sure what's wrong with the CI, it compiles fine on my machine.

**Comment by Grogdunn** [comment]
Well it's an hack... I'll try to implement a sort of render queue ^^ but I'm not confortable with Rust... 

Maybe a complete new window to add the files to be processed at once can be an idea. It's a good excuse to learn some rust

**Pull request closed without merging**
